name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: Shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: pawansharma1802/python-app:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v3

      - name: Install yq (Go binary)
        shell: bash
        run: |
          YQ_VERSION="v4.44.3"
          curl -L "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64" -o yq
          chmod +x yq
          sudo mv ./yq /usr/local/bin/yq
          yq --version

      - name: Modify values.yaml
        shell: bash
        run: |
          echo "Commit: ${{ needs.ci.outputs.commit_id }}"
          yq -i '.image.tag = "${{ needs.ci.outputs.commit_id }}"' charts/python-app/values.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit ${{needs.ci.outputs.commit_id}}'

      - name: Install argocd
        shell: bash
        run: |
          curl -ksSL -o argocd http://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd:80 \
            --plaintext \
            --insecure  \
            --username admin \
            --password  ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app
